export const ADD_PAINTING = 'ADD_PAINTING';
export const ADD_PAINTING_ERROR = 'ADD_PAINTING_ERROR';
export const ADD_PAINTING_SUCCESS = 'ADD_PAINTING_SUCCESS';

export const FETCH_PAINTINGS_ERROR = 'FETCH_PAINTINGS_ERROR';
export const FETCH_PAINTINGS_SUCCESS = 'FETCH_PAINTINGS_SUCCESS';

export const POST_PAINTING_IMAGE_SUCCESS = 'POST_PAINTING_IMAGE';
export const POST_PAINTING_IMAGE_ERROR = 'POST_PAINTING_IMAGE_ERROR';

export const FETCH_PAINTING_START = 'FETCH_PAINTING_START';
export const CLEAR_PAINTING_STORE = 'CLEAR_PAINTING_STORE';
